---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен заполнить поля адреса и ФИО получателя для отправки товаров перед покупкой
  - После оформления заказа корзина должна очищаться
  - Пользователь должен иметь возможность просматривать свои заказы, которые характеризуются датой заказа, суммой заказа, наименованием и количеством товаров
  - Пользователь должен иметь возможность видеть в корзине стоимость товаров
  - Пользователь должен иметь возможность удалить позицию товара в корзине или изменить его количество
  - Пользователь должен иметь возможность выбрать категорию из всех категорий
  - Настройки языка должны сохраняться при перезагрузке страницы
  - Выбор языка должен влиять и на интерфейс, и на информацию о товарах, и на названия категорий и производителей
  - Пользователь не должен иметь возможность в фильтре по цене написать буквы, спецсимволы и неположительные числа
  - Пользователь должен иметь возможность написать в фильтре по цене десятичное число как через точку, так и через запятую
  - Фильтр по цене "от" и "до" должен включать граничные значения
  - Пользователь должен иметь возможность выбрать количества товара для добавления в корзину
  - Рейтинг товара должен визуально отличаться от остальной информации о товаре в карточке товара
  - Значение фильта по цене "до" должно показывать максимальную цену товара при данных значениях фильтрации
  - Значение фильтра по цене "до" должно фильтровать товары по скидочной цене
  - При заходе на сайт пользователю предлагается выбрать город для доставки или дать доступ к геолокации и подтвердить город. Пользователь должен узнать, что это повлияет на стоимость доставки
  - При указании города доставки товары по цене должны фильтроваться с учетом стоимости доставки
  - Пользователь должен выбрать службу доставки при оформлении заказа
  - Пользователь должен иметь возможность фильтровать товары по порядку возрастания (убывания) рейтинга, цены, процентов скидки, сцецпредложениям скидок
  - Пользователь должен видеть количество страниц товаров по заданным им фильтрам и иметь возможность перейти на любую страницу поиска
  - Пользователь должен иметь возможность при вводе ключегого слова в поиске выбрать наиболее подходящий запрос из выпадающего кликабельного списка
  - Пользователь должен иметь возможность перейти на главную страницу магазина при нажатии на название или логотип магазина в шапке
  - Должно появляться уведомление при добавлении товара в корзину и оформлении заказа
  - При удалении позиции из корзины пользователю должен вылазить поп-ап с подтверждением удаления
  - При выборе категории пользователь должен иметь возможность выбирать производителей только из данной категории
  - Пользователь должен иметь возможность выбора валюты для отображения на сайте
  - Пользователь должен иметь возможность убрать категорию из фильтра
  - Пользователь не должен иметь возможность в строке поиска писать что-либо, кроме символов ".,-", букв и цифр
  - Пользователь должен иметь возможность найти товар по артикулу
